// All data here is fictional sample content for a Final Year Project demo.
// Nothing is generated by a real model or fetched from a backend.

export type Finding = {
  region: string
  detail: string
}

export type MockReport = {
  confidence: number
  findings: Finding[]
  impression: string
  plainSummary: string
  visualCaption: string
  // Position of the simulated heatmap overlay, in % of the image box.
  heatmap: { top: number; left: number; width: number; height: number }
}

export const mockReport: MockReport = {
  confidence: 87,
  findings: [
    {
      region: 'Lower left lung field',
      detail:
        'Mild patchy opacity observed, consistent with early-stage pneumonia (lung inflammation).',
    },
    {
      region: 'Heart size',
      detail: 'Cardiac silhouette is within normal limits. No enlargement noted.',
    },
    {
      region: 'Bony structures',
      detail: 'Ribs and spine appear intact with no visible fractures.',
    },
    {
      region: 'Pleural spaces',
      detail: 'No significant fluid collection (pleural effusion) detected.',
    },
  ],
  impression:
    'Findings are most consistent with a mild, early left lower lobe pneumonia. No signs of serious complications on this image.',
  plainSummary:
    "Your chest X-ray shows a small, hazy area in the lower part of your left lung. This usually points to a mild lung infection (pneumonia) that has been caught early. Your heart and bones look normal, and there is no fluid buildup around your lungs. This is very treatable, and your doctor has likely prescribed medicine to help you recover.",
  visualCaption:
    'The highlighted area shows where the X-ray looks slightly cloudier than the surrounding healthy lung. This cloudiness is what suggests a mild infection in your lower left lung.',
  heatmap: { top: 52, left: 30, width: 22, height: 22 },
}

export type Medicine = {
  name: string
  purpose: string
  relation: string
}

export const mockMedicines: Medicine[] = [
  {
    name: 'Amoxicillin 500mg',
    purpose: 'An antibiotic that fights bacterial infections.',
    relation:
      'Prescribed to clear the bacteria causing the mild pneumonia seen in your left lung.',
  },
  {
    name: 'Paracetamol 500mg',
    purpose: 'A pain and fever reducer.',
    relation:
      'Helps ease any fever, body aches, or chest discomfort while your infection heals.',
  },
  {
    name: 'Guaifenesin Syrup',
    purpose: 'A cough expectorant that loosens mucus.',
    relation:
      'Makes it easier to cough up mucus from your lungs, supporting your recovery.',
  },
]

export type SymptomLink = {
  symptom: string
  finding: string
}

export const mockSymptomLinks: SymptomLink[] = [
  { symptom: 'Persistent cough', finding: 'Left lower lung opacity' },
  { symptom: 'Mild fever', finding: 'Lung inflammation' },
  { symptom: 'Chest tightness', finding: 'Left lower lung opacity' },
  { symptom: 'Fatigue', finding: "Body's response to infection" },
]

export type QAMessage = {
  id: string
  role: 'patient' | 'ai'
  text: string
}

export const initialQA: QAMessage[] = [
  {
    id: 'q1',
    role: 'patient',
    text: 'What does this X-ray result mean for me?',
  },
  {
    id: 'a1',
    role: 'ai',
    text: "Your X-ray shows a small area of mild infection in the lower part of your left lung, often called early pneumonia. It was caught early, which is good news. With the medicine your doctor prescribed and some rest, most people recover well within a couple of weeks.",
  },
  {
    id: 'q2',
    role: 'patient',
    text: 'Is this serious? Should I be worried?',
  },
  {
    id: 'a2',
    role: 'ai',
    text: "This appears to be a mild, early-stage infection with no signs of serious complications on your image. It's understandable to feel anxious, but this is a common and very treatable condition. The most important steps are to take your full course of antibiotics and follow up with your doctor.",
  },
]

export const suggestedQuestions = [
  'What does this mean for me?',
  'Is this serious?',
  'How long until I feel better?',
  'When should I see my doctor?',
]

// Canned responses used to fake the assistant when the user sends a question.
export const cannedResponses = [
  "That's a great question. Based on your X-ray, this mild lung infection typically improves within 1 to 2 weeks once you start your antibiotics. Rest, fluids, and finishing your full course of medicine are key. Always check with your doctor if symptoms worsen.",
  "Understandably, this can feel worrying. The good news is your image shows an early, mild finding with no serious complications. Following your prescribed treatment closely gives you the best chance of a smooth recovery.",
  "For your specific situation, it's best to follow up with your doctor if your fever lasts more than 3 days, your breathing becomes difficult, or you feel significantly worse. Otherwise, continue your medicine as prescribed.",
  "Remember, this explanation is designed to help you understand your report in plain language. It does not replace your doctor's advice. Please share any concerns with your healthcare provider.",
]
